---

- name: Install Git
  package:
    name: git
    state: latest

- name: Install ViM
  package:
    name: vim
    state: latest

- name: Install nano
  package:
    name: nano
    state: latest

- name: Install cron
  package:
    name: cron
    state: latest

# Net tools is only available in apt
- name: Install net-tools using apt
  apt:
    name: net-tools
    state: latest
    update_cache: yes

- name: Install telnet
  package:
    name: telnet
    state: latest

- name: Install wget
  package:
    name: wget
    state: latest

- name: Install curl
  package:
    name: curl
    state: latest

- name: Install jq
  package:
    name: jq
    state: latest