# 1) DB server(s): common stuff + DB stuff
- name: Common + DB stuff on db servers
  hosts: db_servers
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - ../dev-vault.yml
  roles:
    - utilities
    - ufw
    - zsh
    - docker
    - postgres_stack
    - postgres_backup

# 2) Backup server(s): common stuff + backup stuff
- name: Common + backup stuff on backup servers
  hosts: backup_servers
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - ../dev-vault.yml
    
  roles:
    - utilities
    - zsh
    - postgres_backup