# 1) DB server(s): common stuff + DB stuff
- name: Common + DB stuff on db servers
  hosts: db_servers
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - ../dev-vault.yml
    
  roles:
    - utilities
    - ufw
    - zsh
    - docker
    - postgres_stack
    - postgres_backup