---

server_name: postgres-server
ansible_user: ansible

postgres_image: "postgres:18"
postgres_container_name: "db"

pgadmin_image: "dpage/pgadmin4:latest"
pgadmin_container_name: "pgadmin"

pgadmin_default_email: "admin@example.com"
pgadmin_default_password: "{{ vault_pgadmin_password }}"

postgres_user: "postgres"
postgres_password: "{{ vault_postgres_password }}"
postgres_db: "main_db"

local_backup_keep_days: 15